### ISSUE TITLE
Profile selection

### ISSUE THREAD

**Issue by MattLish** [UltimateSkyrim/ultimate-skyrim-launcher#35]
Add a menu item to select a profile to launch the game with.
This should launch the MO2 instance with the corresponding profile.

The list of profiles needs to be read from the profiles directory in the mod directory.

MO2 needs to be launched with this specific profile.

No copying/Symlinking is required because these profiles will already be in MO2.

- [x] Prevent running app if no profiles
- [ ] If mod directory changes, re-render profiles

**Comment by RingComics** [comment]
Files are only moved on game start purposely. It is suppose to update the config file
