### ISSUE TITLE
Configure ENB view

### ISSUE THREAD

**Issue by MattLish** [UltimateSkyrim/ultimate-skyrim-launcher#37]
# Configure enb view

Add a view to configure available enbs.

- [ ] New enb profile - Creates a new directory to store enb configuration in
- [ ] Load enb profile
- [ ] Open enb
- [ ] Delete enb

### Additional features
- [ ] Detect if path to an already defined enb is invalid on app startup?
- [ ] Provide default location for storing enbs?
- [ ] Prevent the user from selecting their own directory (and just use one internal to the app) to prevent users from accidentally renaming paths to that enb?

### Outstanding questions

- ~What does load enb do? How is this different to new?~
- ~What does delete enb do? Does this actually delete the enb or just remove it from the launcher?~
Anwered below

**Comment by RingComics** [comment]
Load ENB selects an ENB to use as the current configuration, as opposed to new which adds a new one
Delete ENB should probably do both, but warn users "Hey, this will permanently delete your ENB stuff"

**Comment by MattLish** [comment]
No longer needed once #296 is completed
