### ISSUE TITLE
Change current GFF and ENB solution from copying to symlinking

### ISSUE THREAD

**Issue by RingComics** [UltimateSkyrim/ultimate-skyrim-launcher#41]

**Comment by MattLish** [comment]
@RingComics What is the advantage of using symlinks over copying?
Won't both leave the Skyrim directory unclean?

**Comment by RingComics** [comment]
> @RingComics What is the advantage of using symlinks over copying?
> Won't both leave the Skyrim directory unclean?

The idea was we'd still unlink the files when the game closes. Symlinking then unlinking is just faster than copying and deleting the files @MattLish

**Comment by MattLish** [comment]
Ah, I see. That makes sense, thanks.
Useful to know if we go down the route of linking and unlinking on game start in the future.

**Comment by thomasblasquez** [comment]
@MattLish

Do we still want to do this? Symlinking does mean in-game changes will reflect in the original ENB Preset directory, since the file is just symbolically linked in the SGF, but still physically exists in the Preset folder.

**Comment by MattLish** [comment]
@RingComics I think we should revisit the whole enb concept as a whole. 
I think we need to start from scratch and decide what functionality we actually want to support and then we can decide how we do it.
Personally, I would close this for now and create new issues when we know what we want to support.
